name: Trigger PR Build

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: string
  pull_request:

concurrency:
  group: pr-${{ github.event.inputs.pr_number || github.event.pull_request.number }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - name: Do the thing
        run: echo "Hello World"
